apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: cpms
type: Opaque
data:
  MONGO_USERNAME: YWRtaW4=        # base64("admin")
  MONGO_PASSWORD: YWRtaW4=        # base64("admin")
  JWT_SECRET: JWT_SECRET
  SMTP_PASS: SMTP_PASS
  CLOUDINARY_API_SECRET: CLOUDINARY_API_SECRET
  CLOUDINARY_API_KEY: CLOUDINARY_API_KEY

